// Coach & partner directory data.
//
// Profiles 8–23 below come from the official "Your PathKEY Coach Profile"
// intake form (self-submitted by each coach/partner).
// Profiles 1–7 are earlier entries whose country / language / expertise /
// need tags are still illustrative and will be confirmed via the same form.
//
// status: "strategic" | "affiliate" | "practitioner"
//   strategic    -> Strategic Partner (top-tier, invitation only)
//   affiliate    -> Affiliate Partner
//   practitioner -> Certified Practitioner (not yet an affiliate)
// purpose: any of "one-to-one" | "workshop" | "business-development"
// booking: coach's own direct booking link ("" -> falls back to contact form)
window.COACHES = [
  /* ---------- earlier entries (tags to be confirmed) ---------- */
  {
    id: "ozlen-coksezen",
    booking: "",
    name: "Özlen Çoksezen",
    photo: "coaches-img/ozlen.png",
    title: "Executive Coach & Strategy Consultant",
    country: "Türkiye",
    city: "",
    status: "strategic",
    trainer: "",
    purpose: ["one-to-one", "workshop", "business-development"],
    workMode: ["Online", "In Person"],
    languages: ["Turkish", "English"],
    clients: ["Executives & Senior Leaders", "Organizations"],
    expertise: ["Executive Coaching", "Strategy & Transformation", "Leadership Development"],
    industries: ["Healthcare & Pharmaceuticals", "Professional Services & Consulting"],
    bio: "With over 25 years of senior leadership experience across the international pharmaceutical and medical-device sectors, Özlen helps leaders navigate high uncertainty and transformation. As founder of MAGHA STRATEGY, she designs strategic advisory, coaching and mentoring processes that redefine growth, sharpen decision quality and evolve leadership culture — with PathKEY as one of her most powerful clarity tools.",
    education: ["Executive education in leadership & strategy", "International management background"],
    certifications: ["PathKEY Certified Coach"],
    experience: ["Founder — MAGHA STRATEGY", "Senior leadership roles at Pfizer, Becton Dickinson, Radiometer (Danaher) and Transearch", "Markets across Eastern Europe, the Middle East, Africa and Russia/CIS"],
    linkedin: "",
    website: ""
  },
  {
    id: "vera-saroyan",
    booking: "",
    name: "Vera Saroyan",
    photo: "coaches-img/vera.jpg",
    title: "ICF PCC & PathKEY Certified Coach",
    country: "Türkiye",
    city: "",
    status: "affiliate",
    trainer: "",
    purpose: ["one-to-one", "workshop"],
    workMode: ["Online", "In Person"],
    languages: ["Turkish", "English", "Armenian"],
    clients: ["Executives & Senior Leaders", "Teams", "Students & Youth"],
    expertise: ["Executive Coaching", "Team Coaching & Development", "Student & Youth Coaching"],
    industries: ["Professional Services & Consulting"],
    bio: "After many years in service and management roles, Vera stepped onto the professional coaching path. She specialises in executive, student, team and relationship coaching, and has deep training in emotional intelligence and body language. An ICF-approved PCC, she is currently progressing toward the MCC credential.",
    education: ["Professional coaching education", "Emotional intelligence & body-language training"],
    certifications: ["ICF PCC (MCC in progress)", "PathKEY Certified Coach"],
    experience: ["Executive & manager coaching", "Student, team and relationship coaching", "Service & management leadership background"],
    linkedin: "",
    website: ""
  },
  {
    id: "cumhur-turgut",
    booking: "",
    name: "Cumhur Turgut",
    photo: "coaches-img/cumhur.png",
    title: "Student, Executive & Team Coach",
    country: "Türkiye",
    city: "",
    status: "practitioner",
    trainer: "",
    purpose: ["one-to-one"],
    workMode: ["Online", "In Person"],
    languages: ["Turkish"],
    clients: ["Students & Youth", "Teams", "Executives & Senior Leaders"],
    expertise: ["Student & Youth Coaching", "Executive Coaching", "Team Coaching & Development"],
    industries: ["Education"],
    bio: "Cumhur brings 25 years of teaching experience into the coaching and consulting world. Trained through an ICF-approved program, he specialises in student, executive and team coaching, and is skilled in education consultancy, life coaching, body language and micro-expressions. Throughout his career he has fuelled strong transformations through motivation and communication techniques.",
    education: ["25 years of teaching experience", "Education consultancy background"],
    certifications: ["ICF-approved coaching training"],
    experience: ["Student, executive & team coaching", "Education consultancy & life coaching", "Body language & micro-expressions"],
    linkedin: "",
    website: ""
  },
  {
    id: "emel-kutludur",
    booking: "",
    name: "Emel Kutludur",
    photo: "coaches-img/emel.jpg",
    title: "Student & Youth Coach",
    country: "Türkiye",
    city: "",
    status: "practitioner",
    trainer: "",
    purpose: ["one-to-one"],
    workMode: ["Online", "In Person"],
    languages: ["Turkish"],
    clients: ["Students & Youth"],
    expertise: ["Student & Youth Coaching", "Career Coaching & Guidance"],
    industries: ["Education"],
    bio: "Emel works with young people in student coaching, offering individual support especially to the 12–24 age group. Guiding them to discover their potential, clarify their goals and confidently chart their own paths is a genuine passion of hers.",
    education: ["Student coaching specialisation"],
    certifications: ["PathKEY Certified Coach"],
    experience: ["Individual coaching for ages 12–24", "Potential discovery & goal setting for youth"],
    linkedin: "",
    website: ""
  },
  {
    id: "handan-dirkali",
    booking: "",
    name: "Handan Dirkali",
    photo: "coaches-img/handan.jpg",
    title: "ICF PCC & PathKEY Certified Coach",
    country: "Türkiye",
    city: "",
    status: "affiliate",
    trainer: "",
    purpose: ["one-to-one", "workshop", "business-development"],
    workMode: ["Online", "In Person"],
    languages: ["Turkish", "English"],
    clients: ["Managers & Emerging Leaders", "Students & Youth", "Organizations"],
    expertise: ["Executive Coaching", "Student & Youth Coaching", "Career Coaching & Guidance"],
    industries: ["Education", "Professional Services & Consulting"],
    bio: "As General Manager of Genom Akademi and a trainer, Handan draws on her coaching experience to help individuals discover their potential, managers understand themselves and their teams, and students clarify their goals when choosing a profession. As a PathKEY certified coach, inspiring people and supporting them on their journeys is both a source of pride and responsibility.",
    education: ["Trainer & academy leadership background"],
    certifications: ["ICF PCC", "PathKEY Certified Coach"],
    experience: ["General Manager — Genom Akademi", "Individual & corporate coaching", "Student career guidance"],
    linkedin: "",
    website: ""
  },
  {
    id: "fatih-ilalan",
    booking: "",
    name: "Fatih İlalan",
    photo: "coaches-img/fatih.jpg",
    title: "Team & Executive Coach",
    country: "Türkiye",
    city: "",
    status: "affiliate",
    trainer: "",
    purpose: ["one-to-one", "workshop"],
    workMode: ["Online", "In Person"],
    languages: ["Turkish", "English"],
    clients: ["Teams", "Managers & Emerging Leaders"],
    expertise: ["Team Coaching & Development", "Leadership Development", "Executive Coaching"],
    industries: ["Manufacturing & Industrial", "Entrepreneurship / Startups"],
    bio: "An ICF-approved professional team and executive coach, Fatih helps leaders and teams unlock their potential, supported by his expertise in micro-expressions and body language. As founder and manager of a construction company for eight years, he knows business dynamics first-hand, and brings analytical thinking and a strategic lens — rooted in his engineering background — to every coaching engagement.",
    education: ["Graduate engineering degree", "ICF-approved coach training"],
    certifications: ["ICF-approved Team & Executive Coach"],
    experience: ["Founder & manager of a construction company (8 years)", "Leadership & team coaching", "Micro-expressions & body language"],
    linkedin: "",
    website: ""
  },
  {
    id: "ebru-erisken",
    booking: "",
    name: "Ebru Erişken",
    photo: "coaches-img/ebru.jpg",
    title: "Student & Team Coach",
    country: "Türkiye",
    city: "",
    status: "practitioner",
    trainer: "",
    purpose: ["one-to-one", "workshop"],
    workMode: ["Online", "In Person"],
    languages: ["Turkish", "English"],
    clients: ["Students & Youth", "Teams"],
    expertise: ["Student & Youth Coaching", "Team Coaching & Development", "Career Coaching & Guidance"],
    industries: ["Education"],
    bio: "With over 25 years teaching in a private school and leading a team of teachers academically, Ebru has always prioritised revealing the potential of students and teams, guiding them to discover their strengths and progress confidently toward their goals. As an ICF-trained and PathKEY certified professional coach, she plays an active role in career journeys with strategic and personal support.",
    education: ["25+ years teaching in a private school", "Academic & process leadership of a teaching team"],
    certifications: ["ICF-approved coaching training", "PathKEY Certified Coach"],
    experience: ["Student & team coaching", "Academic team leadership", "Career-journey development support"],
    linkedin: "",
    website: ""
  },

  /* ---------- profiles from the official intake form ---------- */
  {
    id: "dragana-kupresanin",
    booking: "https://calendly.com/imert-concept/the-next-step-method/a1=Strate%C5%A1ka%20analiza%20profesionalnog%20pravca&month=2026-08",
    name: "Dragana Kupresanin",
    photo: "coaches-img/dragana.jpg",
    title: "Career Strategist & Human Potential Consultant",
    country: "Serbia",
    city: "Belgrade",
    status: "strategic",
    trainer: "",
    purpose: ["one-to-one", "workshop", "business-development"],
    workMode: ["Online", "In Person"],
    languages: ["English", "Serbian"],
    clients: ["Entrepreneurs", "Professionals in Career Transition", "Professionals", "Teams"],
    expertise: ["Strategy & Transformation", "Entrepreneurship", "Reskilling & Career Navigation", "Leadership Development", "Team Coaching & Development"],
    industries: ["Education", "Professional Services & Consulting", "Entrepreneurship / Startups"],
    bio: "Dragana Kupresanin is a multidisciplinary career, business and human potential consultant with more than 20 years of experience in entrepreneurship, international client work, education and professional development. She is the CEO of SVEA Visa Consulting and SVEA Edu Consultants, where her work spans international mobility, career development, professional education and advisory services for individuals and organisations. She advises clients on career and business decisions, professional transitions, strengths, development priorities and strategic next steps, combining structured assessment, business insight, communication and human potential development. Her approach is practical, integrative and commercially grounded, with a strong focus on translating insight into clear and actionable direction.",
    education: ["Doctoral Candidate in Business Management", "Master’s Degrees in Economics and Philology", "Master’s Degree in Occupational Therapy", "Psychotherapy Propedeutics and four years of professional training in Transactional Analysis (TA)"],
    certifications: ["BG5® Career & Business Consultant", "POY Level 1 Trainer", "NLP Master Trainer / NLP Trainer — IN (Berlin), IANLP & NLPGS", "Professional Coach — International Association of Coaching Institutes (ICI), Berlin", "Neurolanguage Coach®"],
    experience: ["Founder & CEO — SVEA Visa Consulting & SVEA Edu Consultants — 20+ years of entrepreneurial experience in international consulting, client advisory, education and professional development", "Career & Human Potential Development Consultant — supporting professionals through career transitions, career planning and strategic decision-making", "International Mobility & Business Consulting — international opportunities, relocation processes, education pathways and global career perspectives"],
    linkedin: "https://www.linkedin.com/in/dragana-kupresanin-a816092a/",
    website: "https://draganakupresanin.com/"
  },
  {
    id: "guncem-karayilanoglu",
    booking: "",
    name: "Güncem Karayılanoğlu",
    photo: "coaches-img/guncem.png",
    title: "Professional Coach & Trainer",
    country: "Türkiye",
    city: "İzmir",
    status: "affiliate",
    trainer: "",
    purpose: ["one-to-one", "workshop", "business-development"],
    workMode: ["Online", "In Person"],
    languages: ["Turkish"],
    clients: ["Students & Youth", "Professionals in Career Transition", "Teams", "Entrepreneurs"],
    expertise: ["Team Coaching & Development", "Talent Development", "Student & Youth Coaching", "Reskilling & Career Navigation", "Entrepreneurship"],
    industries: ["Manufacturing & Industrial", "Consumer & Retail", "Construction", "Nonprofit / NGO"],
    bio: "Güncem Karayılanoğlu combines more than 25 years of corporate and managerial experience with professional coaching and training. She accompanies people as they get to know themselves better, recognise their strengths and make more conscious choices in line with their own values. Through voluntary career-development work with children and young people, she supports different age groups in discovering their potential and taking more confident steps toward their future. Her practice brings together experience, observation and a human-centred approach: rather than offering ready-made answers, she opens space for each person to discover their own path and inner voice.",
    education: ["Professional Coaching Program — Genom Akademi (ICF-accredited coach training)", "Professional Training & Facilitation Program — İzgören Akademi"],
    certifications: ["Professional Coaching Certification — Genom Akademi (ICF-accredited)", "Professional Trainer Certification — İzgören Akademi", "Micro-expressions & Body Language Trainer — Genom Akademi", "MBCL & MBCR mindfulness-based programs — Gürçin Gökçebağ Akademi", "Professional Sales Training — Baltaş Group"],
    experience: ["25+ years of corporate and managerial experience across sales, operations, team and general management in the private sector and local government — Kale Group, Karşıyaka Municipality companies", "Professional coaching, training and workshops — individual, executive and career coaching plus corporate training and development workshops at We Akademi", "Voluntary career work with children and young people — Eşit Gelecek Derneği, KOZA Platform"],
    linkedin: "https://www.linkedin.com/in/g%C3%BCncem-karay%C4%B1lano%C4%9Flu-467bba109/",
    website: ""
  },
  {
    id: "sean-michael",
    booking: "",
    name: "Sean Michael",
    photo: "coaches-img/sean.jpg",
    title: "Professional Coach, Consultant & Human Design Analyst",
    country: "United States",
    city: "Central Coast, California",
    status: "affiliate",
    trainer: "",
    purpose: ["one-to-one", "workshop", "business-development"],
    workMode: ["Online"],
    languages: ["English"],
    clients: ["Professionals in Career Transition", "Executives & Senior Leaders", "Professionals", "Managers & Emerging Leaders"],
    expertise: ["Career Coaching & Guidance", "Executive Coaching", "Leadership Development", "Team Coaching & Development", "Organizational Development"],
    industries: ["Healthcare & Pharmaceuticals", "Professional Services & Consulting", "Education", "Nonprofit / NGO"],
    bio: "Sean Michael is a licensed psychotherapist, clinical supervisor, professional coach, consultant and analyst with more than two decades of experience supporting individuals, couples, professionals and organizations. His work integrates psychological insight, relational intelligence, systems thinking and individualized approaches to personal and professional development. He specializes in helping clients understand their natural strengths, decision-making patterns, relationships, vocational direction and the conditions that support greater alignment and effectiveness. He brings a depth-oriented, practical and highly individualized perspective to helping people work and live with greater clarity, integrity and self-understanding.",
    education: ["International Human Design School (IHDS) and BG5 Business Institute — advanced professional certifications and training, including Profit Potential Coaching, Executive Leadership Analysis, Partnership Analysis, and Organizational Communication and Navigation", "Depth Psychology and Archetypal Studies — 35 years of study and applied experience in depth psychology, archetypal systems, relational dynamics and small-group process", "Advanced professional training across individual, relational, organizational and systemic approaches to human development"],
    certifications: ["Licensed Marriage and Family Therapist (LMFT), California", "CAMFT Certified Clinical Supervisor", "IHDS Certified Human Design Professional Analyst", "BG5 Certified Career & Business Consultant", "BG5 Profit Potential Coach"],
    experience: ["35+ years in psychotherapy, coaching, consulting and human development", "Licensed psychotherapist and Certified Clinical Supervisor — individual, couples, relational and professional development", "Individual and organizational consultant — leadership, partnerships, team dynamics, communication and professional alignment"],
    linkedin: "https://www.linkedin.com/in/sean-michael-7b07a722",
    website: "https://www.innerblueprint.net/about"
  },
  {
    id: "veronica-chase",
    booking: "https://veronicabchaseco.com/book-a-readiness-conversation",
    name: "Veronica Chase",
    photo: "coaches-img/veronica.jpg",
    title: "Leadership Consultant, Facilitator & Speaker",
    country: "United States",
    city: "Greater Philadelphia Region",
    status: "strategic",
    trainer: "L1 Trainer",
    purpose: ["one-to-one", "workshop", "business-development"],
    workMode: ["Online", "In Person"],
    languages: ["English"],
    clients: ["Executives & Senior Leaders", "Organizations", "Teams", "Managers & Emerging Leaders"],
    expertise: ["Leadership Development", "Team Coaching & Development", "Talent Development", "Organizational Development"],
    industries: ["Manufacturing & Industrial", "Professional Services & Consulting", "Healthcare & Pharmaceuticals"],
    bio: "Veronica Chase is an Alignment Key Strategic Partner and a learning and organizational effectiveness leader with three decades of experience. She works with leaders, teams and organizations to strengthen self-awareness, leadership effectiveness, collaboration and performance, particularly as AI reshapes roles and ways of working. Her background spans enterprise learning strategy, performance management, leadership development, organizational change and strategic facilitation. Veronica brings a practical, systems-oriented perspective that helps clients translate meaningful insights into clearer decisions, stronger working relationships and sustainable action.",
    education: ["Master of Science in Instructional Design and Technology-Based Learning", "Certified Talent Development Leader — University of North Carolina at Chapel Hill, Kenan-Flagler Business School"],
    certifications: ["Certified Professional in Talent Development (CPTD), ATD", "Certified Change Management Practitioner, PROSCI", "PathKEY Level 1 Trainer"],
    experience: ["Head of Enterprise Learning, major arts & cultural institution (8 years) — built and led the enterprise L&D function for a globally renowned institution with 2 million annual visitors, covering leadership development, coaching, onboarding, performance management, team effectiveness, assessments and learning infrastructure", "Senior Director, Performance and Organizational Effectiveness, Fortune Global 500 organization (10 years) — owned the North American learning and performance agenda for 16,000+ managers and led the senior consultant team", "Senior Performance and Organizational Consultant, MOSAIC Performance Solutions (6 years) — led consulting delivery for Fortune 500 clients including GlaxoSmithKline, Sanofi Pasteur, UPMC and Sony"],
    linkedin: "https://www.linkedin.com/in/veronicabchaseco",
    website: "https://veronicabchaseco.com/"
  },
  {
    id: "vladimir-borachev",
    booking: "",
    name: "Vladimir Borachev",
    photo: "coaches-img/vladimir.jpg",
    title: "Executive Coach & Leadership Enabler",
    country: "Bulgaria",
    city: "Sofia",
    status: "strategic",
    trainer: "",
    purpose: ["one-to-one", "workshop"],
    workMode: ["Online", "In Person"],
    languages: ["English", "Bulgarian"],
    clients: ["Executives & Senior Leaders", "Managers & Emerging Leaders", "Teams"],
    expertise: ["Executive Coaching", "Leadership Development"],
    industries: ["Professional Services & Consulting", "Education", "Entrepreneurship / Startups", "Consumer & Retail", "Technology"],
    bio: "Vladimir is an inspiring educator with solid experience across 11 leadership positions with Xerox and Avon in Central Eastern Europe, Egypt and Turkey. Since 2011 he has actively supported managers at different levels through executive coaching, mentoring, tailor-made leadership programs and keynote speeches. His key areas of interest include personal and leadership development, employee inspiration and performance management, dealing with difficult people and converting aggressive managers. Numerous teams have praised him for his ability to inspire people to develop and to give their best toward team and company goals. He is currently working on his international leadership book, expected to publish in Q1 2027.",
    education: ["Bachelor of Arts in Business Administration — American University in Bulgaria", "MBA — IESE Business School"],
    certifications: ["ICF Professional Certified Coach (PCC)", "iEQ9 Enneagram Accredited Practitioner"],
    experience: ["11 leadership roles with Xerox and Avon across Central Eastern Europe, Egypt and Turkey", "Executive coaching, mentoring and tailor-made leadership programs since 2011", "Keynote speaker on leadership and performance management"],
    linkedin: "https://www.linkedin.com/in/vladimir-borachev/",
    website: "https://www.borachev.com"
  },
  {
    id: "caroline-harris",
    booking: "https://cal.eu/caroline-harris/connectioncall",
    name: "Caroline Harris",
    photo: "coaches-img/carolineharris.jpg",
    title: "Strategic Advisor for Work & Leadership",
    country: "United Kingdom",
    city: "London",
    status: "practitioner",
    trainer: "",
    purpose: ["one-to-one", "workshop", "business-development"],
    workMode: ["Online", "In Person"],
    languages: ["English"],
    clients: ["Entrepreneurs", "Professionals in Career Transition", "Managers & Emerging Leaders"],
    expertise: ["Organizational Development", "Strategy & Transformation", "Entrepreneurship", "Leadership Development"],
    industries: ["Financial Services", "Nonprofit / NGO", "Entrepreneurship / Startups"],
    bio: "Caroline has 18 years’ experience in banking and financial services, leading complex change and transformation across global organisations. She works with individuals, founders and leaders to better understand their strengths, ways of working and the dynamics that shape how they work with others. Combining strategic thinking with Human Design, she brings a practical yet highly personalised perspective to questions of work, leadership and team effectiveness. Her work is grounded in the belief that when people understand and value what they naturally bring, we can create healthier and more effective ways of working together.",
    education: ["BSc Management Studies — Brunel University"],
    certifications: ["BG5 Career & Business Consultant — BG5 Business Institute", "Business Sustainability Management — Cambridge Institute for Sustainability Leadership (CISL)"],
    experience: ["Strategic advisor to start-up founders in climate & impact", "18+ years in financial services, delivering complex transformation programmes across finance, operations and IT", "Organisation design across large organisations and founder-led businesses"],
    linkedin: "https://www.linkedin.com/in/caroline-harris-7a791117/",
    website: "https://www.directionaligned.com"
  },
  {
    id: "pelin-ozkuzey",
    booking: "",
    name: "Pelin Özkuzey",
    photo: "coaches-img/pelin.jpg",
    title: "Executive Coach, Mentor, Trainer & Lecturer",
    country: "Türkiye",
    city: "",
    status: "affiliate",
    trainer: "",
    purpose: ["one-to-one", "workshop", "business-development"],
    workMode: ["Online"],
    languages: ["Turkish", "English"],
    clients: ["Executives & Senior Leaders", "Organizations", "Teams", "Students & Youth", "Professionals"],
    expertise: ["Career Coaching & Guidance", "Executive Coaching", "Leadership Development", "Talent Development", "Strategy & Transformation"],
    industries: ["Education", "Professional Services & Consulting"],
    bio: "Professional coach, mentor, consultant, program and project leader, trainer and lecturer. A researcher working in the fields of brand management and strategy, Pelin has spoken at numerous universities and institutions and runs consulting and training projects and programs for individuals, organizations and universities.",
    education: ["Business Administration, International Business, Management Information Systems, Management"],
    certifications: ["ICF-accredited coach", "PathKEY Certified Coach"],
    experience: ["Consulting and training programs for individuals, organizations and universities", "Speaker at universities and institutions", "Research in brand management and strategy"],
    linkedin: "https://www.linkedin.com/in/pelin-ozkuzey-71223712",
    website: ""
  },
  {
    id: "olga-lavrenova",
    booking: "https://scheduler.zoom.us/olga-ol-ways-net",
    name: "Olga Lavrenova",
    photo: "coaches-img/olga.jpg",
    title: "Executive, Leadership & Career Coach",
    country: "Bulgaria",
    city: "Sofia",
    status: "affiliate",
    trainer: "",
    purpose: ["one-to-one", "workshop"],
    workMode: ["Online", "In Person"],
    languages: ["English", "Bulgarian", "Russian"],
    clients: ["Professionals", "Professionals in Career Transition", "Executives & Senior Leaders", "Managers & Emerging Leaders"],
    expertise: ["Career Coaching & Guidance", "Executive Coaching", "Leadership Development", "Career Transition & Outplacement"],
    industries: ["Consumer & Retail", "Professional Services & Consulting", "Manufacturing & Industrial"],
    bio: "Olga Lavrenova is a former Managing Director of HEINEKEN Bulgaria with 25 years of leadership experience in international corporations, primarily in sales and commercial roles. She has built and led high-performing teams and is known for developing organizations where people’s engagement and business results grow together. Today she works with accomplished leaders and executives who want greater clarity in their decisions, motivation and direction — especially at moments of change or increased responsibility. Olga combines real executive experience and sales expertise with deep reflective coaching, working with teams and peer-to-peer, challenging leaders while creating a space of trust, transparency and genuine care.",
    education: ["Executive MBA — WU Executive Academy, Austria and Carlson School of Management, US", "Corporate executive education — INSEAD"],
    certifications: ["Co-Active practitioner — CTI Co-Active Coaching Training Institute", "BG5 Career and Business Consultant — BG5 Business Institute"],
    experience: ["Managing Director — HEINEKEN Bulgaria", "Senior Director Sales and Distribution — HEINEKEN Russia", "25+ years of executive and leadership experience in enterprise leadership and commerce"],
    linkedin: "https://www.linkedin.com/in/olga-lavrenova-ol-ways",
    website: "https://ol-ways.net/"
  },
  {
    id: "veronique-lecompte",
    booking: "https://calendly.com/veroniquelecompteconseil/30min",
    name: "Véronique Lecompte",
    photo: "coaches-img/veronique.jpg",
    title: "Expert in Career & Professional Development",
    country: "France",
    city: "Paris",
    status: "affiliate",
    trainer: "",
    purpose: ["one-to-one", "workshop", "business-development"],
    workMode: ["Online", "In Person"],
    languages: ["English", "French"],
    clients: ["Entrepreneurs", "Managers & Emerging Leaders", "Professionals"],
    expertise: ["Talent Development", "Entrepreneurship", "Career Coaching & Guidance", "Career Transition & Outplacement", "Leadership Development"],
    industries: ["Technology", "Manufacturing & Industrial", "Energy & Utilities", "Entrepreneurship / Startups", "Professional Services & Consulting"],
    bio: "Véronique brings over 25 years of experience in listed international groups and mid-sized companies, first as a MarCom Director and later as a Senior Consultant advising executives on marketing and communication strategies. She has coordinated and mentored international, multicultural professional networks and, since 2023, has specialized as a BG5 Consultant in career and professional development. A Course Assistant with the BG5 Business Institute, she is also a Certified PathKEY Consultant and an Alignment Key Partner. Drawing on both her corporate leadership experience and these advanced assessment systems, Véronique helps professionals, executives and entrepreneurs gain clarity on their strengths, decision-making and career direction — creating what her clients often describe as a genuine “before and after.”",
    education: ["Executive Master Marketing Management — ESSEC Business School", "French Press Institute — Paris-Assas University", "Master in Business Law — Aix-Marseille University"],
    certifications: ["BG5 Career & Business Consultant Certification", "AI & Digital Marketing Strategy Certification", "Marketing & Communication of CSR Strategy Certification", "Institute for Advanced Studies in National Defence (IHEDN) Certification", "Therapeutic Psychogenealogy Practitioner Certification (in progress)"],
    experience: ["Veolia Water — Communications Director, Brand, Events & Multimedia: coordinated an international network of 25 marcom directors and led the worldwide brand and internet strategy", "Franco-British Chamber of Commerce & Industry — Marketing-Communications Director: built and executed the 3-year strategy supporting 2,000 member companies through Brexit, advising the President and Board on 50+ media interviews", "Cross-Channel Institute Think Tank — Marketing-Communications Director and Coordination Committee member; co-author of the 2017 and 2018 Annual Barometers and the 2020 Transportation Report", "Lecompte Conseil — founder of a MarCom strategy consultancy, now focused on career and professional development and BG5 Partnership Analysis"],
    linkedin: "https://www.linkedin.com/in/veroniquelecompte/",
    website: "https://lecompteconseil.com/"
  },
  {
    id: "nikolina-nikolova",
    booking: "",
    name: "Nikolina Nikolova",
    photo: "coaches-img/nikolina.jpg",
    title: "Career Development Coach | PathKEY Certified Coach | ICF Coach",
    country: "Bulgaria",
    city: "Sofia",
    status: "affiliate",
    trainer: "",
    purpose: ["one-to-one", "workshop"],
    workMode: ["Online", "In Person"],
    languages: ["Bulgarian"],
    clients: ["Students & Youth", "Early-Career Professionals", "Professionals in Career Transition", "Executives & Senior Leaders"],
    expertise: ["Career Coaching & Guidance", "Career Transition & Outplacement", "Student & Youth Coaching", "Reskilling & Career Navigation", "Executive Coaching"],
    industries: ["Healthcare & Pharmaceuticals", "Manufacturing & Industrial", "Professional Services & Consulting", "Financial Services", "Education", "Nonprofit / NGO", "Technology"],
    bio: "Nikolina Nikolova is a Career Development Coach, PathKEY Certified Coach and ICF Coach with over 20 years of experience in HR, organizational development and business consulting. She partners with individuals and organizations to help people identify their strengths, make confident career decisions and navigate professional transitions. Drawing on extensive experience in global business environments and talent development, she combines coaching with practical career development tools to support sustainable growth and long-term career success.",
    education: ["Master’s Degree in Business Administration and Management — University of National and World Economy (UNWE), Sofia, Bulgaria"],
    certifications: ["PathKEY Certified Coach — Alignment Key, Luxembourg", "ICF Accredited Professional Coach Training — Mentor Coaches, Bulgaria", "HR Strategic Business Academy — InYourHands, Bulgaria"],
    experience: ["HR Executive & Business Partner — 20+ years in international organizations across manufacturing, professional services and global business environments", "Leadership & Organizational Development — partnering with senior leaders on talent development, career growth, organizational change and people strategy across multicultural teams", "Career Development & Coaching — supporting professionals in identifying strengths, navigating career transitions and building meaningful career paths"],
    linkedin: "https://www.linkedin.com/in/nikolinanikolova",
    website: ""
  },
  {
    id: "evren-biron",
    booking: "https://tidycal.com/evrenbiron/60-minute-meeting",
    name: "Evren Biron",
    photo: "coaches-img/evren.jpg",
    title: "Leadership & Team Coach, Business Consultant, Corporate Training Facilitator",
    country: "Türkiye",
    city: "Istanbul",
    status: "affiliate",
    trainer: "",
    purpose: ["one-to-one", "workshop", "business-development"],
    workMode: ["Online"],
    languages: ["English", "Turkish"],
    clients: ["Early-Career Professionals", "Managers & Emerging Leaders", "Teams", "Professionals"],
    expertise: ["Leadership Development", "Team Coaching & Development", "Organizational Development", "Career Coaching & Guidance", "Student & Youth Coaching"],
    industries: ["Healthcare & Pharmaceuticals", "Financial Services", "Manufacturing & Industrial"],
    bio: "An ICF Professional Certified Coach (PCC), corporate trainer and consultant with over 20 years of experience in the healthcare sector, including senior leadership roles across service, sales, marketing and business management. Evren provides executive and leadership coaching as well as corporate training in leadership, sales, communication and professional development. He brings extensive experience working in international and multicultural corporate environments, offering a broad perspective on the challenges leaders and professionals face across different cultures and organizational contexts, and combines practical business experience with professional coaching and experiential learning to support meaningful and sustainable development.",
    education: ["M.Sc. in Biomedical Engineering — Istanbul Technical University (İTÜ)", "B.Sc. in Electronics and Telecommunication Engineering — Istanbul Technical University (İTÜ)", "Next Generation Leaders Program — Sabancı University"],
    certifications: ["ICF Professional Certified Coach (PCC)", "Human Design Certified Guide & Analyst — International Human Design School (IHDS)", "PSYCH-K® Facilitator — PSYCH-K® International Centre"],
    experience: ["Co-Founder, Düşformans | Strategy Lead, Kolsara — executive and leadership coaching, corporate training and consultancy focused on leadership, sales, communication, performance, career development and mindset transformation", "20+ years in the healthcare sector across service, sales, marketing and business management, including senior leadership roles", "17+ years at Siemens Healthineers — leadership experience within a global, multicultural organization"],
    linkedin: "https://www.linkedin.com/in/evrenbiron/",
    website: "https://www.dusformans.com"
  },
  {
    id: "mierta-romana-jann",
    booking: "",
    name: "Mierta Romana Jann",
    photo: "coaches-img/mierta.png",
    title: "Senior Executive Coach",
    country: "Switzerland",
    city: "Aarau",
    status: "affiliate",
    trainer: "",
    purpose: ["one-to-one", "workshop", "business-development"],
    workMode: ["Online", "In Person"],
    languages: ["French", "German", "English"],
    clients: ["Early-Career Professionals", "Organizations", "Entrepreneurs", "Professionals"],
    expertise: ["Career Coaching & Guidance", "Career Transition & Outplacement", "Strategy & Transformation", "Entrepreneurship"],
    industries: ["Manufacturing & Industrial", "Professional Services & Consulting", "Education", "Consumer & Retail", "Media & Communications", "Energy & Utilities", "Public Sector"],
    bio: "Mierta is a career coach, systemic coach, Gestalt therapist and trainer for teams and communication, working with individuals and organizations across Switzerland and internationally.",
    education: ["Bachelor in Hotel Management", "Ausbilderin mit eidg. Fachausweis (Swiss Federal Diploma in Training)", "Gestalt Therapist"],
    certifications: ["Systemischer Gestaltcoach (dvtc)", "Gestalttherapeutin IGE", "Ausbilderin mit eidg. Fachausweis", "Lego® Serious Play"],
    experience: ["Senior Executive Consultant", "Gestalt Therapist", "Trainer for teams and communication"],
    linkedin: "https://www.linkedin.com/in/miertaromanajann",
    website: "https://www.miertaromana.ch"
  },
  {
    id: "aynur-gormus",
    booking: "",
    name: "Aynur Görmüş",
    photo: "coaches-img/aynur.jpg",
    title: "Performance Coach, Mentor & Leadership Trainer",
    country: "Türkiye",
    city: "İstanbul",
    status: "affiliate",
    trainer: "",
    purpose: ["one-to-one", "workshop", "business-development"],
    workMode: ["Online", "In Person"],
    languages: ["Turkish"],
    clients: ["Teams", "Managers & Emerging Leaders", "Early-Career Professionals", "Professionals"],
    expertise: ["Career Coaching & Guidance", "Leadership Development", "Team Coaching & Development", "Sales Coaching", "Organizational Development"],
    industries: ["Healthcare & Pharmaceuticals", "Financial Services", "Manufacturing & Industrial"],
    bio: "Starting her career as a laboratory technician in 1994, Aynur spent 26 years at Siemens Healthineers, taking on leadership roles across procurement, finance and — primarily — sales, including managing the Service Sales team for the last 10 years of her corporate career. Drawing on her experience of working across cultures and with measurable goals, she believes that effective leadership starts with understanding people. Today she works as a coach and facilitator, supporting individuals and teams in self-awareness, mindset management, goal setting and achievement, sales and communication skills. With a strong commitment to continuous learning and personal development, she helps her clients recognize their potential and enhance their performance in a meaningful and sustainable way.",
    education: ["Next Generation Leadership Program — Sabancı University", "Biomedical Device Technology — Kocaeli University"],
    certifications: ["ICF Professional Certified Coach (PCC)"],
    experience: ["Co-Founder & Coach — Düşformans: supporting individuals and teams in self-awareness, mindset transformation, goal achievement, sales, communication and personal performance", "Service Sales Manager — Siemens Healthineers: 10 years leading the Service Sales team with a focus on sales performance, team leadership and customer relationships", "26 years across sales, procurement and financial operations within a global healthcare technology organization"],
    linkedin: "https://www.linkedin.com/in/aynur-görmüş/",
    website: "https://www.dusformans.com"
  },
  {
    id: "aleksandra-kasmi",
    booking: "",
    name: "Aleksandra Kasmi",
    photo: "coaches-img/aleksandra.jpg",
    title: "Founder of Future Group & Leadership Coach",
    country: "Albania",
    city: "Tirana",
    status: "affiliate",
    trainer: "",
    purpose: ["one-to-one", "workshop", "business-development"],
    workMode: ["Online", "In Person"],
    languages: ["Albanian", "English"],
    clients: ["Organizations", "Teams", "Managers & Emerging Leaders", "Executives & Senior Leaders"],
    expertise: ["Leadership Development", "Team Coaching & Development", "Entrepreneurship", "Talent Development", "Executive Coaching"],
    industries: ["Consumer & Retail", "Public Sector", "Entrepreneurship / Startups", "Financial Services"],
    bio: "With over 28 years of professional experience in people development, leadership, sales management and organizational transformation, Aleksandra supports leaders, executives and organizations in achieving sustainable growth through strong leadership, effective communication and high-performing teams. A Master Coach and Senior Training Expert, she has held executive and senior leadership roles in multinational companies, public institutions and entrepreneurial ecosystems across Albania, the Western Balkans and internationally. She is known for her ability to inspire, motivate and develop people, combining strategic thinking with practical, results-driven solutions.",
    education: ["IMBA — Bournemouth University, UK (Chevening Scholar)", "PCD — Noble Manhattan Coaching, UK"],
    certifications: ["PathKEY Certified Coach", "Noble Manhattan Coaching — Practitioner Coach Diploma (PCD)"],
    experience: ["Founder — Future Group", "Founder — Bangkok Sales Network", "Country Manager Albania — Avon Cosmetics"],
    linkedin: "https://www.linkedin.com/in/aleksandra-kasmi",
    website: "https://www.futuregroup.al"
  },
  {
    id: "daniel-priest",
    booking: "",
    name: "Daniel Priest",
    photo: "coaches-img/danielpriest.jpg",
    title: "Executive Coach & Team Efficiency Engineer",
    country: "United States",
    city: "Southern California",
    status: "affiliate",
    trainer: "",
    purpose: ["one-to-one", "workshop", "business-development"],
    workMode: ["Online", "In Person"],
    languages: ["English"],
    clients: ["Teams", "Entrepreneurs", "Managers & Emerging Leaders", "Professionals in Career Transition"],
    expertise: ["Team Coaching & Development", "Career Transition & Outplacement", "Organizational Development", "Reskilling & Career Navigation", "Entrepreneurship"],
    industries: ["Technology", "Entrepreneurship / Startups", "Public Sector", "Education"],
    bio: "Dan Priest spent thirteen years at Microsoft in field Enterprise Sales and Marketing, a number of startups, and eleven years at GroupOne IT leading enterprise-wide technology change programs across more than 100 client organizations. The primary work life lesson learned is results track the team, not the technology. As the world of work accelerates with AI as a force multiplier, people and their teamwork matter more than ever — is each person doing work suited to how they actually operate? As a Certified PathKEY Consultant, Dan now specializes in helping individuals and teams identify the conditions that drive real productivity, applying a team-first lens to career transitions and group performance.",
    education: ["BS Electrical Engineering"],
    certifications: ["PathKEY Certified Coach", "BG5 Certified Consultant", "PMP — Project Management Institute"],
    experience: ["11 years leading enterprise-wide technology change programs — GroupOne IT, across 100+ client organizations", "13 years in field Enterprise Sales & Marketing — Microsoft", "40 years working with and leading cross-functional teams"],
    linkedin: "https://www.linkedin.com/in/danielpriest/",
    website: "https://wa-analytics.com/"
  },
  {
    id: "agnieszka-magusiak-sajdak",
    booking: "https://calendly.com/agnieszkamagusiak",
    name: "Agnieszka Magusiak-Sajdak",
    photo: "coaches-img/agnieszka.jpg",
    title: "Business Consultant, Accredited Executive Coach & Mentor",
    country: "Poland & Spain",
    city: "",
    status: "affiliate",
    trainer: "",
    purpose: ["one-to-one", "workshop", "business-development"],
    workMode: ["Online", "In Person"],
    languages: ["Polish", "English"],
    clients: ["Executives & Senior Leaders", "Professionals in Career Transition", "Entrepreneurs", "Organizations"],
    expertise: ["Leadership Development", "Executive Coaching", "Strategy & Transformation", "Entrepreneurship", "Organizational Development"],
    industries: ["Technology", "Manufacturing & Industrial", "Professional Services & Consulting"],
    bio: "Agnieszka Magusiak-Sajdak is a business consultant and mentor with over 20 years of international leadership and management experience across Europe, Asia and Mexico. Throughout her corporate career, she led strategic projects, organizational transformations and international teams, including building a manufacturing operation in Mexico from the ground up. Today, she works with leaders, entrepreneurs and professionals navigating important career and business decisions, combining real-world business experience with a deep understanding of individual strengths, natural potential and professional identity. Her work helps clients gain clarity, make more conscious decisions, and build careers and businesses that are both effective and genuinely aligned with who they are.",
    education: ["MBA & DBA, Business Management & Marketing — WSB-NLU"],
    certifications: ["EIA Practitioner (EMCC)", "ICF Member", "Certified Gallup Strengths Coach", "Certified BG5 Career & Business Consultant", "Business Coaching Diploma — Advanced Level 2, ACTP (PwC)", "GPW Growth Academy (GPW & EY)"],
    experience: ["Business Consultant, Executive Coach & Mentor — running an independent practice in coaching, mentoring, strengths-based consulting and business training for leaders and organizations", "Production Plant Director & President — SMX Rubber Company S.A. de C.V., San Luis Potosí, Mexico: built and launched a 12M USD manufacturing operation with 150 employees", "Trade & Marketing Department Manager — SRC S.A.: led national and international sales strategy and supported the acquisition of international entities in Germany, China and France"],
    linkedin: "https://www.linkedin.com/in/magusiakagnieszka",
    website: "https://www.agnieszkamagusiak.com"
  },
  {
    id: "manuela-barrera-cazzaniga",
    name: "Manuela Barrera Cazzaniga",
    photo: "coaches-img/manuela.jpg",
    title: "Human Design for Career & Business, BG5 Consultant",
    country: "Switzerland",
    city: "Zurich",
    status: "affiliate",
    trainer: "",
    purpose: ["one-to-one", "workshop"],
    workMode: ["Online"],
    languages: ["German"],
    clients: ["Students & Youth", "Teams", "Organizations", "Entrepreneurs"],
    expertise: ["Career Transition & Outplacement", "Team Coaching & Development", "Student & Youth Coaching", "Entrepreneurship", "Reskilling & Career Navigation"],
    industries: ["Professional Services & Consulting", "Education", "Media & Communications", "Public Sector", "Nonprofit / NGO", "Entrepreneurship / Startups"],
    bio: "Manuela Barrera Cazzaniga helps individuals and teams understand where they create their strongest professional impact — both on their own and in collaboration with others. She works with BG5, the business application of Human Design, addressing the root cause rather than the surface. This approach resolves recurring issues such as dissatisfaction, inefficiency, or poor role fit sustainably, rather than just treating the symptoms. She helps people and organizations recognize where a person's natural strengths truly take hold, and where friction signals a misalignment that no amount of effort can fix. She also trains executive and career coaches so they can uncover their clients' hidden strengths and guide them more effectively. Her work supports clients in bringing themselves — and the people they work with — to where their impact truly lands, making the difference in an AI-shaped era.",
    education: ["Human Design for Career & Business — BG5 Business Institute", "BG5 Career and Business Professional — BG5 Business Institute"],
    certifications: [],
    experience: ["5+ years in Human Design for Career & Business, BG5", "10+ years in Entrepreneurship", "15+ years in PR, Marketing & Online Campaigning, product development and sales — including work for a cantonal education department, tourism, an NGO, a cloud service provider, and financial services firms"],
    linkedin: "https://www.linkedin.com/in/manuela-barrera-cazzaniga/",
    website: "https://manuelabarrera.ch"
  }
];
